import type { WebsiteContentSectionDefaults } from "../types";

export function getBoardOfTrusteesDefaults(): WebsiteContentSectionDefaults {
  return {
    placeholders: {
      title: "Juan Jose Jamora III",
      subtitle: "Chairman Emeritus",
      paragraph: "",
      visionParagraph: "",
      missionParagraph: "",
      icon: "",
      imageUrl: "",
      cardPlacement: "1",
    },
    cards: [
      {
        entryKey: "featured_1",
        title: "Juan Jose Jamora III",
        subtitle: "Chairman Emeritus",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 1,
        group: "featured",
      },
      {
        entryKey: "featured_2",
        title: "Ma. Luisa Segovia",
        subtitle: "President",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 2,
        group: "featured",
      },
      {
        entryKey: "officer_1",
        title: "Herminio Maravilla",
        subtitle: "Chairman",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 3,
        group: "officers",
      },
      {
        entryKey: "officer_2",
        title: "Jose Paolo Treñas",
        subtitle: "Vice President",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 4,
        group: "officers",
      },
      {
        entryKey: "officer_3",
        title: "Allen Son Tan",
        subtitle: "Corporate Secretary",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 5,
        group: "officers",
      },
      {
        entryKey: "officer_4",
        title: "Phillipp Chua",
        subtitle: "Treasurer",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 6,
        group: "officers",
      },
      {
        entryKey: "officer_5",
        title: "Atty. George Que",
        subtitle: "Legal Counsel",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 7,
        group: "officers",
      },
      {
        entryKey: "trustee_1",
        title: "Francis De la Cruz",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 8,
        group: "trustees",
      },
      {
        entryKey: "trustee_2",
        title: "Jose Hautea, Jr.",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 9,
        group: "trustees",
      },
      {
        entryKey: "trustee_3",
        title: "Philip Joel Lataquin",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 10,
        group: "trustees",
      },
      {
        entryKey: "trustee_4",
        title: "Jose Layson, Jr.",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 11,
        group: "trustees",
      },
      {
        entryKey: "trustee_5",
        title: "Arsenio Rafael III",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 12,
        group: "trustees",
      },
      {
        entryKey: "trustee_6",
        title: "Atty. Fritzie Diez-Treñas",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 13,
        group: "trustees",
      },
      {
        entryKey: "trustee_7",
        title: "Engr. Terence Uygongco",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 14,
        group: "trustees",
      },
      {
        entryKey: "trustee_8",
        title: "Anatole Dan Viray",
        subtitle: "Trustee",
        paragraph: "",
        icon: "",
        imageUrl: "",
        cardPlacement: 15,
        group: "trustees",
      },
    ],
  };
}
