name: 🐛 Bug Report
description: Report a bug to help us improve
title: "[BUG] "
labels:
  - bug
type: bug
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What happened? A clear and concise description of the bug.
      placeholder: Tell us what broke...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
    validations:
      required: true

  - type: textarea
    id: possible_cause
    attributes:
      label: Possible Cause
      description: Any ideas what might be causing this?
    validations:
      required: false

  - type: input
    id: browser
    attributes:
      label: Browser 
      placeholder: Chrome 120, Safari 17, etc.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Logs
      description: Paste logs or attach screenshots.
      render: bash
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Anything else we should know?
    validations:
      required: false
