"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createActionClient } from "@/lib/supabase/server";

import {
  createSectorSchema,
  updateSectorSchema,
} from "@/lib/validation/sector/sectorSchema";

export async function createSector(input: z.infer<typeof createSectorSchema>) {
  const parsed = createSectorSchema.parse(input);

  const supabase = await createActionClient();

  // Note: sectorId is generated by default as identity in the database schema
  const { data, error } = await supabase
    .from("Sector")
    .insert({
      sectorName: parsed.sectorName,
    })
    .select("sectorId")
    .single();

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin");
  return { id: data.sectorId };
}

export async function updateSector(input: z.infer<typeof updateSectorSchema>) {
  const parsed = updateSectorSchema.parse(input);

  const supabase = await createActionClient();

  const { data, error } = await supabase
    .from("Sector")
    .update({
      sectorName: parsed.sectorName,
    })
    .eq("sectorId", parsed.id)
    .select("sectorId")
    .single();

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin");
  return { id: data.sectorId };
}

const sectorDeletionPreviewSchema = z.object({
  id: z.number(),
});

export async function getSectorDeletionPreview(
  input: z.infer<typeof sectorDeletionPreviewSchema>,
) {
  const parsed = sectorDeletionPreviewSchema.parse(input);

  const supabase = await createActionClient();

  const [membersResult, sectorsResult] = await Promise.all([
    supabase
      .from("BusinessMember")
      .select("businessMemberId, businessName")
      .eq("sectorId", parsed.id)
      .order("businessName", { ascending: true }),
    supabase
      .from("Sector")
      .select("sectorId, sectorName")
      .neq("sectorId", parsed.id)
      .order("sectorName", { ascending: true }),
  ]);

  if (membersResult.error) {
    throw new Error(membersResult.error.message);
  }

  if (sectorsResult.error) {
    throw new Error(sectorsResult.error.message);
  }

  return {
    members: membersResult.data ?? [],
    alternativeSectors: sectorsResult.data ?? [],
  };
}

const deleteSectorSchema = z.object({
  id: z.number(),
  reassignSectorId: z.number().optional(),
  memberReassignments: z
    .array(
      z.object({
        memberId: z.string().min(1),
        sectorId: z.number(),
      }),
    )
    .optional(),
});

export async function deleteSector(input: z.infer<typeof deleteSectorSchema>) {
  const parsed = deleteSectorSchema.parse(input);

  const supabase = await createActionClient();

  const { data: members, error: membersError } = await supabase
    .from("BusinessMember")
    .select("businessMemberId")
    .eq("sectorId", parsed.id);

  if (membersError) {
    throw new Error(membersError.message);
  }

  const membersToReassign = members ?? [];
  const hasMembers = membersToReassign.length > 0;
  const hasBulkReassign = Boolean(parsed.reassignSectorId);
  const memberReassignments = parsed.memberReassignments ?? [];
  const hasMemberSpecificAssignments = memberReassignments.length > 0;

  if (hasMembers) {
    if (!hasBulkReassign && !hasMemberSpecificAssignments) {
      throw new Error(
        "Assign every member to a different sector before deleting this one.",
      );
    }

    if (hasBulkReassign && parsed.reassignSectorId === parsed.id) {
      throw new Error("Members cannot be moved to the sector being deleted.");
    }

    if (hasMemberSpecificAssignments) {
      const assignedIds = new Set(
        memberReassignments.map((assignment) => assignment.memberId),
      );

      const missingAssignments = membersToReassign.filter(
        (member) => !assignedIds.has(member.businessMemberId),
      );

      if (missingAssignments.length > 0) {
        throw new Error(
          "Provide a new sector for every member in this sector before deleting.",
        );
      }

      await Promise.all(
        memberReassignments.map(async (assignment) => {
          if (assignment.sectorId === parsed.id) {
            throw new Error(
              "Members cannot be moved to the sector being deleted.",
            );
          }

          const { error: updateError } = await supabase
            .from("BusinessMember")
            .update({ sectorId: assignment.sectorId })
            .eq("businessMemberId", assignment.memberId);

          if (updateError) {
            throw new Error(updateError.message);
          }
        }),
      );
    } else if (parsed.reassignSectorId) {
      const { error: reassignmentError } = await supabase
        .from("BusinessMember")
        .update({ sectorId: parsed.reassignSectorId })
        .eq("sectorId", parsed.id);

      if (reassignmentError) {
        throw new Error(reassignmentError.message);
      }
    }
  }

  const { error } = await supabase
    .from("Sector")
    .delete()
    .eq("sectorId", parsed.id);

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin/manage-sector");
  return { success: true };
}
