"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createActionClient } from "@/lib/supabase/server";

const createSectorSchema = z.object({
  sectorName: z.string().min(1, "Sector name is required"),
});

type CreateSectorInput = z.infer<typeof createSectorSchema>;

export async function createSector(input: CreateSectorInput) {
  const parsed = createSectorSchema.parse(input);

  const supabase = await createActionClient();

  // Note: sectorId is generated by default as identity in the database schema
  const { data, error } = await supabase
    .from("Sector")
    .insert({
      sectorName: parsed.sectorName,
    })
    .select("sectorId")
    .single();

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin");
  return { id: data.sectorId };
}
const deleteSectorSchema = z.object({
  id: z.number(),
});

export async function deleteSector(input: z.infer<typeof deleteSectorSchema>) {
  const parsed = deleteSectorSchema.parse(input);

  const supabase = await createActionClient();
  const { error } = await supabase
    .from("Sector")
    .delete()
    .eq("sectorId", parsed.id);

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin/manage-sector");
  return { success: true };
}
