"use server";

import { revalidatePath } from "next/cache";
import { z } from "zod";
import { createActionClient } from "@/lib/supabase/server";

import {
  createSectorSchema,
  updateSectorSchema,
} from "@/lib/validation/sector/sectorSchema";

function escapeLikeString(str: string) {
  return str.replace(/[%_\\]/g, "\\$&");
}

export async function createSector(input: z.infer<typeof createSectorSchema>) {
  const parsed = createSectorSchema.parse(input);

  const supabase = await createActionClient();

  // Escape special characters to treat input as literal string, not pattern
  const safeSectorName = escapeLikeString(parsed.sectorName);

  const { data: existingSectors, error: checkError } = await supabase
    .from("Sector")
    .select("sectorId")
    .ilike("sectorName", safeSectorName)
    .limit(1);

  if (checkError) {
    throw new Error(checkError.message);
  }

  if (existingSectors && existingSectors.length > 0) {
    throw new Error("Sector with this name already exists");
  }

  // Note: sectorId is generated by default as identity in the database schema
  const { data, error } = await supabase
    .from("Sector")
    .insert({
      sectorName: parsed.sectorName,
    })
    .select("sectorId")
    .single();

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin");
  return { id: data.sectorId };
}

export async function updateSector(input: z.infer<typeof updateSectorSchema>) {
  const parsed = updateSectorSchema.parse(input);

  const supabase = await createActionClient();

  const { data, error } = await supabase
    .from("Sector")
    .update({
      sectorName: parsed.sectorName,
    })
    .eq("sectorId", parsed.id)
    .select("sectorId")
    .single();

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin");
  return { id: data.sectorId };
}

const deleteSectorSchema = z.object({
  id: z.number(),
});

export async function deleteSector(input: z.infer<typeof deleteSectorSchema>) {
  const parsed = deleteSectorSchema.parse(input);

  const supabase = await createActionClient();
  const { error } = await supabase
    .from("Sector")
    .delete()
    .eq("sectorId", parsed.id);

  if (error) {
    throw new Error(error.message);
  }

  revalidatePath("/admin/manage-sector");
  return { success: true };
}
